### ISSUE TITLE
Not an Issue but didn't knew how to share this with devs

### ISSUE THREAD

**Issue by sasukedotca** [exjam/wiiu-emu#42]
https://github.com/Exzap/Cemu/releases
Anyone can use the source code of this other emu and try to update the emulator :)
edit: if he wants to share it.. seems like there is only a readme file

**Comment by smb123w64gb** [comment]
But there is always debug stuff left in the exe...
"J:\wxWidgets302\include\wx/tracker.h" 
So his gui is wxWidgets...  And on is J disk
Another thing to point out is that the dev of that emu is using OpenGL 3.3, This one is using DirectX12. 
We could See improvement in this one, Since DX12 give more room to work with.
Until then the interpreter and Gfx needs to mature so game's will actually run.

**Comment by sasukedotca** [comment]
he seems to be able to render 3d, buggy with some textures. not bad.. at all

**Comment by exjam** [comment]
We are aware of this effort, it is a shame that it is not open source - we will continue to work on this project.

**Comment by sasukedotca** [comment]
https://i.imgur.com/lNRJKeX.png
So just in case someone is wondering, he is not sharing the source code, too bad, some games are in menu or broken 3D, but I'm sure you guys will catch up :)
Thanks for the efforts..
